use std::path::Path;

use crate::db;
use crate::db::GhostDb;
use crate::knowledge;

use super::types::ImportError;

/// Ensure that a topic hierarchy exists in the DB. For "dioxus/docs",
/// ensures both "dioxus" and "dioxus/docs" exist as topic rows.
/// Returns the leaf topic ID.
pub async fn ensure_topic_hierarchy(db: &GhostDb, topic_name: &str) -> Result<String, ImportError> {
    let parts: Vec<&str> = topic_name.split('/').collect();
    let mut last_id = String::new();

    for i in 0..parts.len() {
        let name = parts[..=i].join("/");
        last_id = db::knowledge::find_or_create_topic(db, &name).await?;
    }

    Ok(last_id)
}

/// Write `_import.toml` alongside imported references to record import metadata.
pub fn write_import_toml(
    workspace: &Path,
    topic_name: &str,
    source_type: &str,
    source_url: &str,
    version_ref: Option<&str>,
    ref_count: usize,
) -> Result<(), ImportError> {
    let ref_dir = workspace.join("references").join(topic_name);
    std::fs::create_dir_all(&ref_dir)?;

    let mut toml = format!(
        "# Auto-generated by ghost reference import\n\
         source_type = \"{source_type}\"\n\
         source_url = \"{source_url}\"\n\
         ref_count = {ref_count}\n"
    );
    if let Some(ver) = version_ref {
        toml.push_str(&format!("version_ref = \"{ver}\"\n"));
    }

    let import_path = ref_dir.join("_import.toml");
    std::fs::write(&import_path, toml)?;

    // Also ensure index notes exist for the topic hierarchy
    knowledge::ensure_index_notes(workspace, topic_name)
        .map_err(|e| ImportError::Io(std::io::Error::other(e.to_string())))?;

    Ok(())
}
