use std::path::Path;

use serde::Serialize;

use crate::db;
use crate::db::GhostDb;
use crate::knowledge;

use super::types::{ImportConfigJson, ImportError};

/// Ensure that a topic hierarchy exists in the DB. For "dioxus/docs",
/// ensures both "dioxus" and "dioxus/docs" exist as topic rows.
/// Returns the leaf topic ID.
pub async fn ensure_topic_hierarchy(db: &GhostDb, topic_name: &str) -> Result<String, ImportError> {
    let parts: Vec<&str> = topic_name.split('/').collect();
    let mut last_id = String::new();

    for i in 0..parts.len() {
        let name = parts[..=i].join("/");
        last_id = db::knowledge::find_or_create_topic(db, &name).await?;
    }

    Ok(last_id)
}

/// Flat structure serialized into `_import.toml` — merges `ImportConfigJson`
/// fields with runtime values (version_ref, ref_count).
#[derive(Serialize)]
struct ImportToml {
    source_type: String,
    source_url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    version_ref: Option<String>,
    ref_count: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    git_ref: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    paths: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    extensions: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    max_depth: Option<usize>,
    #[serde(skip_serializing_if = "Option::is_none")]
    max_pages: Option<usize>,
}

/// Write `_import.toml` alongside imported references to record import metadata.
pub fn write_import_toml(
    workspace: &Path,
    topic_name: &str,
    config: &ImportConfigJson,
    version_ref: Option<&str>,
    ref_count: usize,
) -> Result<(), ImportError> {
    let ref_dir = workspace.join("references").join(topic_name);
    std::fs::create_dir_all(&ref_dir)?;

    let import_toml = ImportToml {
        source_type: config.source_type.clone(),
        source_url: config.source_url.clone(),
        version_ref: version_ref.map(String::from),
        ref_count,
        git_ref: config.git_ref.clone(),
        paths: config.paths.clone(),
        extensions: config.extensions.clone(),
        max_depth: config.max_depth,
        max_pages: config.max_pages,
    };

    let content = format!(
        "# Auto-generated by ghost reference import\n{}",
        toml::to_string_pretty(&import_toml)
            .map_err(|e| ImportError::Io(std::io::Error::other(e.to_string())))?
    );

    let import_path = ref_dir.join("_import.toml");
    std::fs::write(&import_path, content)?;

    // Also ensure index notes exist for the topic hierarchy
    knowledge::ensure_index_notes(workspace, topic_name)
        .map_err(|e| ImportError::Io(std::io::Error::other(e.to_string())))?;

    Ok(())
}
