/// Central registry of all files bundled with the ghost binary.
///
/// The `BUNDLED_FILES` array is auto-generated by `build.rs` from the
/// `assets/` directory. The workspace-relative path of each file equals
/// its path relative to `assets/`. To add a new bundled file, just drop
/// it in `assets/` — no Rust changes needed.
///
/// Shadow copies live in `.bundled/{path}` inside the workspace. On each
/// boot, `compute_changes` compares the old shadow against the new bundle
/// to detect real upstream changes and three-way merges user modifications.
use std::path::Path;

/// A file bundled into the ghost binary via `include_str!`.
pub struct BundledFile {
    /// Workspace-relative path, e.g. "skills/system-management/skill.md"
    pub path: &'static str,
    /// File content (from include_str!)
    pub content: &'static str,
}

// Generated by build.rs from assets/ and docs/src/content/
include!(concat!(env!("OUT_DIR"), "/bundled_files.rs"));

/// Returns the complete list of files bundled with this binary.
pub fn bundled_files() -> &'static [BundledFile] {
    BUNDLED_FILES
}

/// Returns the documentation pages bundled with this binary.
pub fn bundled_docs() -> &'static [BundledFile] {
    BUNDLED_DOCS
}

/// Install bundled docs to `references/ghost/docs/` in the workspace.
///
/// Writes only files whose content has changed and removes stale files
/// that are no longer in the bundle, so after this call the directory
/// exactly mirrors the bundled docs.
///
/// Returns the number of files written (new + updated).
pub fn install_docs(workspace: &Path) -> Result<usize, std::io::Error> {
    let docs_dir = workspace.join("references/ghost/docs");
    std::fs::create_dir_all(&docs_dir)?;

    let mut written = 0;

    // Collect the set of expected relative paths for stale-file cleanup
    let mut expected: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();

    for doc in bundled_docs() {
        let dest = docs_dir.join(doc.path);
        expected.insert(dest.clone());

        let needs_write = match std::fs::read_to_string(&dest) {
            Ok(existing) => existing != doc.content,
            Err(_) => true,
        };

        if needs_write {
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&dest, doc.content)?;
            written += 1;
        }
    }

    // Remove stale files not in the current bundle
    remove_stale_files(&docs_dir, &expected)?;

    Ok(written)
}

/// Recursively remove files under `dir` that are not in `expected`,
/// then prune empty directories.
fn remove_stale_files(
    dir: &Path,
    expected: &std::collections::HashSet<std::path::PathBuf>,
) -> Result<(), std::io::Error> {
    for entry in std::fs::read_dir(dir)?.filter_map(std::result::Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            remove_stale_files(&path, expected)?;
            // Remove directory if now empty
            if path.read_dir()?.next().is_none() {
                std::fs::remove_dir(&path)?;
            }
        } else if !expected.contains(&path) {
            std::fs::remove_file(&path)?;
        }
    }
    Ok(())
}

/// Install all bundled files to the workspace, always overwriting.
/// Also writes shadow copies to `.bundled/` for future change detection.
/// Creates parent directories as needed.
pub fn install_all(workspace: &Path) -> Result<(), std::io::Error> {
    for file in bundled_files() {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;

        // Write shadow copy
        let shadow = workspace.join(".bundled").join(file.path);
        if let Some(parent) = shadow.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&shadow, file.content)?;
    }
    Ok(())
}

/// Write a shadow copy for a single file path.
fn write_shadow(workspace: &Path, path: &str, content: &str) -> Result<(), std::io::Error> {
    let shadow = workspace.join(".bundled").join(path);
    if let Some(parent) = shadow.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&shadow, content)
}

// ── Change detection ────────────────────────────────────────────────

use similar::{ChangeTag, TextDiff};

use crate::merge3::{MergeResult, merge3};

/// Result of comparing bundled files against the workspace.
pub struct BundledChanges {
    /// Files that exist in bundle but not in workspace (and have no shadow).
    pub new: Vec<&'static BundledFile>,
    /// Bundle changed but user didn't touch workspace — safe to overwrite.
    pub auto_updates: Vec<AutoUpdate>,
    /// Both sides changed, merge succeeded without conflicts.
    pub clean_merges: Vec<CleanMerge>,
    /// Both sides changed, merge has conflict markers.
    pub conflicts: Vec<ConflictedMerge>,
    /// Files no longer in bundle that the user didn't modify — safe to delete.
    pub clean_removals: Vec<String>,
    /// Files no longer in bundle that the user modified — needs interactive decision.
    pub modified_removals: Vec<String>,
}

/// Bundle changed, workspace matches old shadow — safe auto-update.
pub struct AutoUpdate {
    pub path: &'static str,
    pub bundled_content: &'static str,
}

/// Both sides changed, three-way merge produced a clean result.
pub struct CleanMerge {
    pub path: &'static str,
    pub merged_content: String,
    pub diff: String,
    pub bundled_content: &'static str,
}

/// Both sides changed, three-way merge produced conflict markers.
pub struct ConflictedMerge {
    pub path: &'static str,
    pub conflict_content: String,
    pub bundled_content: &'static str,
    /// The user's workspace content before merge (for showing diffs).
    pub workspace_content: String,
}

impl BundledChanges {
    /// Whether there are changes that require interactive user decision via Discord.
    pub fn has_interactive_updates(&self) -> bool {
        !self.conflicts.is_empty() || !self.modified_removals.is_empty()
    }
}

/// Compare bundled files against the workspace using `.bundled/` shadows.
pub fn compute_changes(workspace: &Path) -> BundledChanges {
    let mut new = Vec::new();
    let mut auto_updates = Vec::new();
    let mut clean_merges = Vec::new();
    let mut conflicts = Vec::new();

    let current_paths: std::collections::HashSet<&str> =
        bundled_files().iter().map(|f| f.path).collect();

    for file in bundled_files() {
        let shadow_path = workspace.join(".bundled").join(file.path);
        let workspace_path = workspace.join(file.path);

        let shadow = std::fs::read_to_string(&shadow_path).ok();
        let ws_content = std::fs::read_to_string(&workspace_path).ok();

        match (shadow, ws_content) {
            // No shadow but workspace already has exact bundle content → skip
            (None, Some(ref ws)) if ws == file.content => {}
            // Shadow exists and matches new bundle → no upstream change, skip
            (Some(ref s), _) if s == file.content => {}
            // Shadow != bundle, workspace == shadow → user didn't touch it
            (Some(ref s), Some(ref ws)) if ws == s => {
                auto_updates.push(AutoUpdate {
                    path: file.path,
                    bundled_content: file.content,
                });
            }
            // No shadow (new or diverged), or shadow missing workspace → treat as new
            (None, None) | (None, Some(_)) | (Some(_), None) => {
                new.push(file);
            }
            // Shadow != bundle, workspace != shadow → three-way merge
            (Some(ref s), Some(ref ws)) => match merge3(s, ws, file.content) {
                MergeResult::Clean(merged) => {
                    let diff = generate_diff(ws, &merged);
                    clean_merges.push(CleanMerge {
                        path: file.path,
                        merged_content: merged,
                        diff,
                        bundled_content: file.content,
                    });
                }
                MergeResult::Conflict(conflict) => {
                    conflicts.push(ConflictedMerge {
                        path: file.path,
                        conflict_content: conflict,
                        bundled_content: file.content,
                        workspace_content: ws.clone(),
                    });
                }
            },
        }
    }

    // Detect removed: scan `.bundled/` for paths not in current bundle.
    // Split into clean (user didn't modify → silent delete) vs modified (needs prompt).
    let mut clean_removals = Vec::new();
    let mut modified_removals = Vec::new();
    for path in scan_shadow_dir(workspace) {
        if current_paths.contains(path.as_str()) {
            continue;
        }
        let shadow = std::fs::read_to_string(workspace.join(".bundled").join(&path)).ok();
        let ws_content = std::fs::read_to_string(workspace.join(&path)).ok();
        match (shadow, ws_content) {
            // Workspace matches shadow (or both missing) → user didn't modify
            (Some(ref s), Some(ref ws)) if s == ws => clean_removals.push(path),
            (_, None) => clean_removals.push(path),
            // Workspace differs from shadow → user modified
            _ => modified_removals.push(path),
        }
    }

    BundledChanges {
        new,
        auto_updates,
        clean_merges,
        conflicts,
        clean_removals,
        modified_removals,
    }
}

/// Recursively scan `.bundled/` and return workspace-relative paths.
fn scan_shadow_dir(workspace: &Path) -> Vec<String> {
    let bundled_dir = workspace.join(".bundled");
    let mut paths = Vec::new();
    if bundled_dir.is_dir() {
        collect_files_recursive(&bundled_dir, &bundled_dir, &mut paths);
    }
    paths
}

fn collect_files_recursive(base: &Path, dir: &Path, paths: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(std::result::Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect_files_recursive(base, &path, paths);
        } else if let Some(s) = path.strip_prefix(base).ok().and_then(|r| r.to_str()) {
            paths.push(s.to_string());
        }
    }
}

/// Generate a unified diff between old (workspace) and new (bundled) content.
pub fn generate_diff(old: &str, new: &str) -> String {
    let diff = TextDiff::from_lines(old, new);
    let mut output = String::new();
    for change in diff.iter_all_changes() {
        let sign = match change.tag() {
            ChangeTag::Delete => "-",
            ChangeTag::Insert => "+",
            ChangeTag::Equal => " ",
        };
        output.push_str(sign);
        output.push_str(change.as_str().unwrap_or(""));
        if !change.as_str().unwrap_or("").ends_with('\n') {
            output.push('\n');
        }
    }
    output
}

/// Apply all non-interactive changes: new files, auto-updates, clean merges,
/// and clean removals. These are safe to apply without user confirmation.
pub fn apply_silent_updates(
    workspace: &Path,
    changes: &BundledChanges,
) -> Result<(), std::io::Error> {
    // Install new files: write workspace + shadow
    for file in &changes.new {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;
        write_shadow(workspace, file.path, file.content)?;
    }

    // Auto-updates: bundle changed, user didn't touch → safe overwrite
    for update in &changes.auto_updates {
        let dest = workspace.join(update.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, update.bundled_content)?;
        write_shadow(workspace, update.path, update.bundled_content)?;
    }

    // Clean merges: both sides changed, no overlap → apply merged result
    for merge in &changes.clean_merges {
        let dest = workspace.join(merge.path);
        std::fs::write(&dest, &merge.merged_content)?;
        write_shadow(workspace, merge.path, merge.bundled_content)?;
    }

    // Clean removals: user didn't modify → safe to delete
    for path in &changes.clean_removals {
        let _ = std::fs::remove_file(workspace.join(path));
        let _ = std::fs::remove_file(workspace.join(".bundled").join(path));
    }

    Ok(())
}

/// The user's decisions about conflicts and modified removals.
pub struct InteractiveDecision {
    /// Conflict paths where the user chose "Take update" (overwrite with bundle).
    pub take_update_paths: Vec<String>,
    /// Modified removal paths where the user chose "Delete".
    pub accepted_deletions: Vec<String>,
}

impl InteractiveDecision {
    pub fn accept_all(changes: &BundledChanges) -> Self {
        Self {
            take_update_paths: changes
                .conflicts
                .iter()
                .map(|c| c.path.to_string())
                .collect(),
            accepted_deletions: changes.modified_removals.clone(),
        }
    }

    pub fn reject_all() -> Self {
        Self {
            take_update_paths: Vec::new(),
            accepted_deletions: Vec::new(),
        }
    }
}

/// Apply user decisions for conflicts and modified removals.
pub fn apply_interactive_updates(
    workspace: &Path,
    changes: &BundledChanges,
    decision: &InteractiveDecision,
) -> Result<(), std::io::Error> {
    for conflict in &changes.conflicts {
        if decision
            .take_update_paths
            .contains(&conflict.path.to_string())
        {
            // "Take update" → overwrite with bundle version
            let dest = workspace.join(conflict.path);
            std::fs::write(&dest, conflict.bundled_content)?;
        }
        // "Keep mine" → don't touch workspace file
        // Either way, update shadow so this conflict won't re-trigger
        write_shadow(workspace, conflict.path, conflict.bundled_content)?;
    }

    for path in &changes.modified_removals {
        if decision.accepted_deletions.contains(path) {
            // "Delete" → remove workspace file
            let _ = std::fs::remove_file(workspace.join(path));
        }
        // Either way, remove shadow (file no longer in bundle)
        let _ = std::fs::remove_file(workspace.join(".bundled").join(path));
    }

    Ok(())
}

// ── Discord update dialog ───────────────────────────────────────────

use crate::interfaces::discord::components_v2::*;
use serenity::http::Http;
use serenity::model::id::ChannelId;

/// Present conflicts and modified removals to the user via Discord.
/// Silent changes (new, auto-updates, clean merges, clean removals) are
/// already applied before this is called.
pub async fn prompt_interactive_updates_via_discord(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> InteractiveDecision {
    let mut parts = Vec::new();
    if !changes.conflicts.is_empty() {
        parts.push(format!(
            "{} file{} with conflicts",
            changes.conflicts.len(),
            if changes.conflicts.len() == 1 {
                ""
            } else {
                "s"
            }
        ));
    }
    if !changes.modified_removals.is_empty() {
        parts.push(format!(
            "{} removed file{} you modified",
            changes.modified_removals.len(),
            if changes.modified_removals.len() == 1 {
                ""
            } else {
                "s"
            }
        ));
    }
    let summary = format!(
        "**Workspace Update — Action Required**\n{}",
        parts.join(", "),
    );

    let components = vec![container(
        vec![
            text_display(&summary),
            action_row(vec![
                button("Accept All", "bundled_accept_all", 3),
                button("Review", "bundled_review", 1),
                button("Reject All", "bundled_reject_all", 4),
            ]),
        ],
        Some(0x5865F2),
    )];

    let msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
        Ok(msg) => msg,
        Err(e) => {
            tracing::error!("Failed to send bundled update dialog: {e}");
            return InteractiveDecision::reject_all();
        }
    };

    loop {
        let Some(custom_id) = rx.recv().await else {
            return InteractiveDecision::reject_all();
        };

        match custom_id.as_str() {
            "bundled_accept_all" => {
                let done = vec![container(
                    vec![text_display("**Workspace Update** — All updates accepted.")],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return InteractiveDecision::accept_all(changes);
            }
            "bundled_reject_all" => {
                let done = vec![container(
                    vec![text_display(
                        "**Workspace Update** — Keeping your versions.",
                    )],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return InteractiveDecision::reject_all();
            }
            "bundled_review" => {
                let reviewing = vec![container(
                    vec![text_display("**Workspace Update** — Reviewing changes...")],
                    Some(0x5865F2),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &reviewing).await;
                return Box::pin(review_interactive_files(changes, http, channel_id, rx)).await;
            }
            _ => continue,
        }
    }
}

/// Present each conflict and modified removal one by one.
async fn review_interactive_files(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> InteractiveDecision {
    let mut take_update_paths: Vec<String> = Vec::new();
    let mut accepted_deletions: Vec<String> = Vec::new();
    let total = changes.conflicts.len() + changes.modified_removals.len();

    // Review conflicts
    for (i, conflict) in changes.conflicts.iter().enumerate() {
        let counter = format!("[{}/{}]", i + 1, total);

        // Show what changes if user takes the update (user's version → bundle)
        let diff = generate_diff(&conflict.workspace_content, conflict.bundled_content);
        let diff_display = truncate_diff_for_discord(&diff);

        let content = format!(
            "{counter} **{}** — conflict\nYour changes conflict with an update.\n\
             ```diff\n{}\n```",
            conflict.path, diff_display
        );

        let file_id = conflict.path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Keep mine", &format!("bundled_file_reject:{file_id}"), 2),
                    button("Take update", &format!("bundled_file_accept:{file_id}"), 3),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send conflict review: {e}");
                // On error, keep user's version (safe default)
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                take_update_paths.push(conflict.path.to_string());
                let done = vec![container(
                    vec![text_display(&format!(
                        "**{}** — taking update",
                        conflict.path
                    ))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!(
                        "**{}** — keeping yours",
                        conflict.path
                    ))],
                    Some(0xFEE75C),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    // Review modified removals
    for (i, path) in changes.modified_removals.iter().enumerate() {
        let counter = format!("[{}/{}]", changes.conflicts.len() + i + 1, total);
        let content = format!(
            "{counter} **{path}**\n\
             This file was removed from defaults, but you have local modifications.",
        );

        let file_id = path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Keep", &format!("bundled_file_reject:{file_id}"), 2),
                    button("Delete", &format!("bundled_file_accept:{file_id}"), 4),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send removal review: {e}");
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                accepted_deletions.push(path.clone());
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — deleted"))],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — kept"))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    InteractiveDecision {
        take_update_paths,
        accepted_deletions,
    }
}

fn truncate_diff_for_discord(diff: &str) -> String {
    if diff.len() > 3400 {
        let end = diff.floor_char_boundary(3400);
        let truncated = &diff[..end];
        let remaining_lines = diff[end..].lines().count();
        format!("{truncated}\n... and {remaining_lines} more lines")
    } else {
        diff.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn new_files_detected() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
        assert!(changes.clean_removals.is_empty());
        assert!(changes.modified_removals.is_empty());
        assert!(!changes.new.is_empty());
    }

    #[test]
    fn unchanged_files_not_flagged() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.new.is_empty());
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
        assert!(changes.clean_removals.is_empty());
        assert!(changes.modified_removals.is_empty());
    }

    #[test]
    fn modified_workspace_file_not_flagged_without_bundle_change() {
        // User modified a file but bundle hasn't changed — should NOT
        // be flagged (shadow == bundle means no upstream change).
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let first = &bundled_files()[0];
        std::fs::write(dir.path().join(first.path), "user modified content").unwrap();
        let changes = compute_changes(dir.path());
        // Shadow == bundle, so no change detected regardless of workspace
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
    }

    #[test]
    fn clean_removal_when_user_didnt_modify() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        // Shadow and workspace have the same content (user didn't modify)
        let shadow_dir = dir.path().join(".bundled/skills/old-skill");
        std::fs::create_dir_all(&shadow_dir).unwrap();
        std::fs::write(shadow_dir.join("skill.md"), "old").unwrap();

        let ws_dir = dir.path().join("skills/old-skill");
        std::fs::create_dir_all(&ws_dir).unwrap();
        std::fs::write(ws_dir.join("skill.md"), "old").unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.clean_removals.len(), 1);
        assert_eq!(changes.clean_removals[0], "skills/old-skill/skill.md");
        assert!(changes.modified_removals.is_empty());
    }

    #[test]
    fn modified_removal_when_user_changed_file() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        // Shadow has original content, workspace has user modification
        let shadow_dir = dir.path().join(".bundled/skills/old-skill");
        std::fs::create_dir_all(&shadow_dir).unwrap();
        std::fs::write(shadow_dir.join("skill.md"), "old").unwrap();

        let ws_dir = dir.path().join("skills/old-skill");
        std::fs::create_dir_all(&ws_dir).unwrap();
        std::fs::write(ws_dir.join("skill.md"), "user modified this").unwrap();

        let changes = compute_changes(dir.path());
        assert!(changes.clean_removals.is_empty());
        assert_eq!(changes.modified_removals.len(), 1);
        assert_eq!(changes.modified_removals[0], "skills/old-skill/skill.md");
    }

    #[test]
    fn diff_generation_works() {
        let diff = generate_diff("old content\nline 2\n", "new content\nline 2\n");
        assert!(diff.contains("-old content"));
        assert!(diff.contains("+new content"));
    }

    #[test]
    fn silent_updates_installs_new_files() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        apply_silent_updates(dir.path(), &changes).unwrap();

        for file in bundled_files() {
            assert!(
                dir.path().join(file.path).exists(),
                "Missing workspace file: {}",
                file.path
            );
            assert!(
                dir.path().join(".bundled").join(file.path).exists(),
                "Missing shadow file: {}",
                file.path
            );
        }
    }

    #[test]
    fn interactive_reject_keeps_user_version() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        let first = &bundled_files()[0];

        // Set up a conflict scenario: shadow != bundle, workspace != shadow,
        // changes overlap so merge3 produces a conflict.
        let base = "line A\nline B\nline C\n";
        let user_version = "user A\nline B\nline C\n";
        write_shadow(dir.path(), first.path, base).unwrap();
        std::fs::write(dir.path().join(first.path), user_version).unwrap();

        let changes = compute_changes(dir.path());

        // Apply silent updates (clean merges get auto-applied)
        apply_silent_updates(dir.path(), &changes).unwrap();

        if !changes.conflicts.is_empty() {
            // Reject all conflicts → keep user's version
            let decision = InteractiveDecision::reject_all();
            apply_interactive_updates(dir.path(), &changes, &decision).unwrap();

            let content = std::fs::read_to_string(dir.path().join(first.path)).unwrap();
            assert_eq!(content, user_version);

            // Shadow still updated so conflict won't re-trigger
            let shadow =
                std::fs::read_to_string(dir.path().join(".bundled").join(first.path)).unwrap();
            assert_eq!(shadow, first.content);
        }
    }

    #[test]
    fn install_all_writes_shadows() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        for file in bundled_files() {
            let shadow = dir.path().join(".bundled").join(file.path);
            assert!(shadow.exists(), "Missing shadow: {}", file.path);
            let content = std::fs::read_to_string(&shadow).unwrap();
            assert_eq!(
                content, file.content,
                "Shadow content mismatch: {}",
                file.path
            );
        }
    }

    #[test]
    fn auto_update_when_user_didnt_modify() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        let first = &bundled_files()[0];
        // Simulate old shadow (different from current bundle)
        let old = "old bundle content";
        std::fs::write(dir.path().join(first.path), old).unwrap();
        write_shadow(dir.path(), first.path, old).unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.auto_updates.len(), 1);
        assert_eq!(changes.auto_updates[0].path, first.path);
    }

    #[test]
    fn install_docs_writes_all_files() {
        let dir = TempDir::new().unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, bundled_docs().len());

        for doc in bundled_docs() {
            let dest = dir.path().join("references/ghost/docs").join(doc.path);
            let content = std::fs::read_to_string(&dest).unwrap();
            assert_eq!(content, doc.content);
        }
    }

    #[test]
    fn install_docs_skips_unchanged() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, 0);
    }

    #[test]
    fn install_docs_removes_stale_files() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file
        let stale = dir.path().join("references/ghost/docs/old-page.md");
        std::fs::write(&stale, "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale.exists(), "stale file should be removed");
    }

    #[test]
    fn install_docs_removes_empty_stale_dirs() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file in a stale subdirectory
        let stale_dir = dir.path().join("references/ghost/docs/old-section");
        std::fs::create_dir_all(&stale_dir).unwrap();
        std::fs::write(stale_dir.join("page.md"), "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale_dir.exists(), "stale directory should be removed");
    }
}
