/// Central registry of all files bundled with the ghost binary.
///
/// The `BUNDLED_FILES` array is auto-generated by `build.rs` from the
/// `assets/` directory. The workspace-relative path of each file equals
/// its path relative to `assets/`. To add a new bundled file, just drop
/// it in `assets/` — no Rust changes needed.
///
/// Shadow copies live in `.bundled/{path}` inside the workspace. On each
/// boot, `compute_changes` compares the old shadow against the new bundle
/// to detect real upstream changes and three-way merges user modifications.
use std::path::Path;

/// A file bundled into the ghost binary via `include_str!`.
pub struct BundledFile {
    /// Workspace-relative path, e.g. "skills/system-management/skill.md"
    pub path: &'static str,
    /// File content (from include_str!)
    pub content: &'static str,
}

// Generated by build.rs from assets/ and docs/src/content/
include!(concat!(env!("OUT_DIR"), "/bundled_files.rs"));

/// Returns the complete list of files bundled with this binary.
pub fn bundled_files() -> &'static [BundledFile] {
    BUNDLED_FILES
}

/// Returns the documentation pages bundled with this binary.
pub fn bundled_docs() -> &'static [BundledFile] {
    BUNDLED_DOCS
}

/// Install bundled docs to `references/ghost/docs/` in the workspace.
///
/// Writes only files whose content has changed and removes stale files
/// that are no longer in the bundle, so after this call the directory
/// exactly mirrors the bundled docs.
///
/// Returns the number of files written (new + updated).
pub fn install_docs(workspace: &Path) -> Result<usize, std::io::Error> {
    let docs_dir = workspace.join("references/ghost/docs");
    std::fs::create_dir_all(&docs_dir)?;

    let mut written = 0;

    // Collect the set of expected relative paths for stale-file cleanup
    let mut expected: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();

    for doc in bundled_docs() {
        let dest = docs_dir.join(doc.path);
        expected.insert(dest.clone());

        let needs_write = match std::fs::read_to_string(&dest) {
            Ok(existing) => existing != doc.content,
            Err(_) => true,
        };

        if needs_write {
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&dest, doc.content)?;
            written += 1;
        }
    }

    // Remove stale files not in the current bundle
    remove_stale_files(&docs_dir, &expected)?;

    Ok(written)
}

/// Recursively remove files under `dir` that are not in `expected`,
/// then prune empty directories.
fn remove_stale_files(
    dir: &Path,
    expected: &std::collections::HashSet<std::path::PathBuf>,
) -> Result<(), std::io::Error> {
    for entry in std::fs::read_dir(dir)?.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            remove_stale_files(&path, expected)?;
            // Remove directory if now empty
            if path.read_dir()?.next().is_none() {
                std::fs::remove_dir(&path)?;
            }
        } else if !expected.contains(&path) {
            std::fs::remove_file(&path)?;
        }
    }
    Ok(())
}

/// Install all bundled files to the workspace, always overwriting.
/// Also writes shadow copies to `.bundled/` for future change detection.
/// Creates parent directories as needed.
pub fn install_all(workspace: &Path) -> Result<(), std::io::Error> {
    for file in bundled_files() {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;

        // Write shadow copy
        let shadow = workspace.join(".bundled").join(file.path);
        if let Some(parent) = shadow.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&shadow, file.content)?;
    }
    Ok(())
}

/// Write a shadow copy for a single file path.
fn write_shadow(workspace: &Path, path: &str, content: &str) -> Result<(), std::io::Error> {
    let shadow = workspace.join(".bundled").join(path);
    if let Some(parent) = shadow.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(&shadow, content)
}

// ── Change detection ────────────────────────────────────────────────

use similar::{ChangeTag, TextDiff};

use crate::merge3::{MergeResult, merge3};

/// Result of comparing bundled files against the workspace.
pub struct BundledChanges {
    /// Files that exist in bundle but not in workspace (and have no shadow).
    pub new: Vec<&'static BundledFile>,
    /// Bundle changed but user didn't touch workspace — safe to overwrite.
    pub auto_updates: Vec<AutoUpdate>,
    /// Both sides changed, merge succeeded without conflicts.
    pub clean_merges: Vec<CleanMerge>,
    /// Both sides changed, merge has conflict markers.
    pub conflicts: Vec<ConflictedMerge>,
    /// Paths in `.bundled/` that are no longer in the current bundle.
    pub removed: Vec<String>,
}

/// Bundle changed, workspace matches old shadow — safe auto-update.
pub struct AutoUpdate {
    pub path: &'static str,
    pub bundled_content: &'static str,
}

/// Both sides changed, three-way merge produced a clean result.
pub struct CleanMerge {
    pub path: &'static str,
    pub merged_content: String,
    pub diff: String,
    pub bundled_content: &'static str,
}

/// Both sides changed, three-way merge produced conflict markers.
pub struct ConflictedMerge {
    pub path: &'static str,
    pub conflict_content: String,
    pub bundled_content: &'static str,
}

impl BundledChanges {
    pub fn has_updates(&self) -> bool {
        !self.clean_merges.is_empty() || !self.conflicts.is_empty() || !self.removed.is_empty()
    }
}

/// Compare bundled files against the workspace using `.bundled/` shadows.
pub fn compute_changes(workspace: &Path) -> BundledChanges {
    let mut new = Vec::new();
    let mut auto_updates = Vec::new();
    let mut clean_merges = Vec::new();
    let mut conflicts = Vec::new();

    let current_paths: std::collections::HashSet<&str> =
        bundled_files().iter().map(|f| f.path).collect();

    for file in bundled_files() {
        let shadow_path = workspace.join(".bundled").join(file.path);
        let workspace_path = workspace.join(file.path);

        let shadow = std::fs::read_to_string(&shadow_path).ok();
        let ws_content = std::fs::read_to_string(&workspace_path).ok();

        match (shadow, ws_content) {
            // No shadow: first time seeing this file
            (None, None) => {
                new.push(file);
            }
            // No shadow but workspace file exists: treat as new if bundle
            // differs from workspace, otherwise skip
            (None, Some(ref ws)) if ws == file.content => {
                // Workspace already has exact bundle content, skip
            }
            (None, Some(_)) => {
                // Workspace has something but no shadow — new bundled file
                new.push(file);
            }
            // Shadow exists and matches new bundle → no upstream change, skip
            (Some(ref s), _) if s == file.content => {
                // Bundle hasn't changed since last install — skip
            }
            // Shadow != bundle, workspace == shadow → user didn't touch it
            (Some(ref s), Some(ref ws)) if ws == s => {
                auto_updates.push(AutoUpdate {
                    path: file.path,
                    bundled_content: file.content,
                });
            }
            // Shadow != bundle, workspace missing → treat as new
            (Some(_), None) => {
                new.push(file);
            }
            // Shadow != bundle, workspace != shadow → three-way merge
            (Some(ref s), Some(ref ws)) => match merge3(s, ws, file.content) {
                MergeResult::Clean(merged) => {
                    let diff = generate_diff(ws, &merged);
                    clean_merges.push(CleanMerge {
                        path: file.path,
                        merged_content: merged,
                        diff,
                        bundled_content: file.content,
                    });
                }
                MergeResult::Conflict(conflict) => {
                    conflicts.push(ConflictedMerge {
                        path: file.path,
                        conflict_content: conflict,
                        bundled_content: file.content,
                    });
                }
            },
        }
    }

    // Detect removed: scan `.bundled/` for paths not in current bundle
    let removed = scan_shadow_dir(workspace)
        .into_iter()
        .filter(|p| !current_paths.contains(p.as_str()))
        .collect();

    BundledChanges {
        new,
        auto_updates,
        clean_merges,
        conflicts,
        removed,
    }
}

/// Recursively scan `.bundled/` and return workspace-relative paths.
fn scan_shadow_dir(workspace: &Path) -> Vec<String> {
    let bundled_dir = workspace.join(".bundled");
    let mut paths = Vec::new();
    if bundled_dir.is_dir() {
        collect_files_recursive(&bundled_dir, &bundled_dir, &mut paths);
    }
    paths
}

fn collect_files_recursive(base: &Path, dir: &Path, paths: &mut Vec<String>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            collect_files_recursive(base, &path, paths);
        } else if let Some(s) = path.strip_prefix(base).ok().and_then(|r| r.to_str()) {
            paths.push(s.to_string());
        }
    }
}

/// Generate a unified diff between old (workspace) and new (bundled) content.
pub fn generate_diff(old: &str, new: &str) -> String {
    let diff = TextDiff::from_lines(old, new);
    let mut output = String::new();
    for change in diff.iter_all_changes() {
        let sign = match change.tag() {
            ChangeTag::Delete => "-",
            ChangeTag::Insert => "+",
            ChangeTag::Equal => " ",
        };
        output.push_str(sign);
        output.push_str(change.as_str().unwrap_or(""));
        if !change.as_str().unwrap_or("").ends_with('\n') {
            output.push('\n');
        }
    }
    output
}

/// The user's decisions about which updates to apply.
pub struct UpdateDecision {
    pub accepted_paths: Vec<String>,
    pub accepted_deletions: Vec<String>,
}

impl UpdateDecision {
    pub fn accept_all(changes: &BundledChanges) -> Self {
        Self {
            accepted_paths: changes
                .clean_merges
                .iter()
                .map(|c| c.path.to_string())
                .collect(),
            accepted_deletions: changes.removed.clone(),
        }
    }

    pub fn reject_all() -> Self {
        Self {
            accepted_paths: Vec::new(),
            accepted_deletions: Vec::new(),
        }
    }
}

/// Apply the user's update decisions to the workspace.
pub fn apply_updates(
    workspace: &Path,
    changes: &BundledChanges,
    decision: &UpdateDecision,
) -> Result<(), std::io::Error> {
    // Install new files: write workspace + shadow
    for file in &changes.new {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;
        write_shadow(workspace, file.path, file.content)?;
    }

    // Auto-updates: write workspace + shadow
    for update in &changes.auto_updates {
        let dest = workspace.join(update.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, update.bundled_content)?;
        write_shadow(workspace, update.path, update.bundled_content)?;
    }

    // Clean merges: accepted → write merged_content to workspace,
    // bundled_content to shadow. Rejected → still update shadow.
    for merge in &changes.clean_merges {
        if decision.accepted_paths.contains(&merge.path.to_string()) {
            let dest = workspace.join(merge.path);
            std::fs::write(&dest, &merge.merged_content)?;
        }
        // Always update shadow to new bundle content
        write_shadow(workspace, merge.path, merge.bundled_content)?;
    }

    // Conflicts: write conflict_content to workspace, bundled_content to shadow
    for conflict in &changes.conflicts {
        let dest = workspace.join(conflict.path);
        std::fs::write(&dest, &conflict.conflict_content)?;
        write_shadow(workspace, conflict.path, conflict.bundled_content)?;
    }

    // Accepted deletions: delete workspace + shadow
    for path in &decision.accepted_deletions {
        let dest = workspace.join(path);
        let _ = std::fs::remove_file(&dest);
        let shadow = workspace.join(".bundled").join(path);
        let _ = std::fs::remove_file(&shadow);
    }

    // Rejected deletions: still remove shadow (file no longer bundled)
    for path in &changes.removed {
        if !decision.accepted_deletions.contains(path) {
            let shadow = workspace.join(".bundled").join(path);
            let _ = std::fs::remove_file(&shadow);
        }
    }

    Ok(())
}

// ── Discord update dialog ───────────────────────────────────────────

use crate::interfaces::discord::components_v2::*;
use serenity::http::Http;
use serenity::model::id::ChannelId;

/// Present bundled file changes to the user via Discord and wait for their
/// decision. Returns the set of accepted file paths and accepted deletions.
pub async fn prompt_updates_via_discord(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> UpdateDecision {
    let mut parts = Vec::new();
    if !changes.clean_merges.is_empty() {
        parts.push(format!("{} files merged", changes.clean_merges.len()));
    }
    if !changes.conflicts.is_empty() {
        parts.push(format!("{} files with conflicts", changes.conflicts.len()));
    }
    if !changes.removed.is_empty() {
        parts.push(format!("{} files removed", changes.removed.len()));
    }
    let summary = format!("**Workspace Update Available**\n{}", parts.join(", "),);

    let components = vec![container(
        vec![
            text_display(&summary),
            action_row(vec![
                button("Accept All", "bundled_accept_all", 3),
                button("Review", "bundled_review", 1),
                button("Reject All", "bundled_reject_all", 4),
            ]),
        ],
        Some(0x5865F2),
    )];

    let msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
        Ok(msg) => msg,
        Err(e) => {
            tracing::error!("Failed to send bundled update dialog: {e}");
            return UpdateDecision::accept_all(changes);
        }
    };

    loop {
        let Some(custom_id) = rx.recv().await else {
            return UpdateDecision::accept_all(changes);
        };

        match custom_id.as_str() {
            "bundled_accept_all" => {
                let done = vec![container(
                    vec![text_display("**Workspace Update** — All changes accepted.")],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return UpdateDecision::accept_all(changes);
            }
            "bundled_reject_all" => {
                let done = vec![container(
                    vec![text_display("**Workspace Update** — All changes rejected.")],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return UpdateDecision::reject_all();
            }
            "bundled_review" => {
                let reviewing = vec![container(
                    vec![text_display("**Workspace Update** — Reviewing changes...")],
                    Some(0x5865F2),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &reviewing).await;
                return review_files(changes, http, channel_id, rx).await;
            }
            _ => continue,
        }
    }
}

/// Present each changed file one by one with Accept/Reject buttons.
async fn review_files(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> UpdateDecision {
    let mut accepted_paths: Vec<String> = Vec::new();
    let mut accepted_deletions: Vec<String> = Vec::new();
    let total = changes.clean_merges.len() + changes.removed.len();

    // Review clean merges
    for (i, merge) in changes.clean_merges.iter().enumerate() {
        let counter = format!("[{}/{}]", i + 1, total);

        // Truncate diff for Discord's 4000 char limit
        let diff_display = if merge.diff.len() > 3400 {
            let end = merge.diff.floor_char_boundary(3400);
            let truncated = &merge.diff[..end];
            let remaining_lines = merge.diff[end..].lines().count();
            format!("{truncated}\n... and {remaining_lines} more lines")
        } else {
            merge.diff.clone()
        };

        let content = format!(
            "{counter} **{}**\n```diff\n{}\n```",
            merge.path, diff_display
        );

        let file_id = merge.path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Accept", &format!("bundled_file_accept:{file_id}"), 3),
                    button("Reject", &format!("bundled_file_reject:{file_id}"), 4),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send file review: {e}");
                accepted_paths.push(merge.path.to_string());
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                accepted_paths.push(merge.path.to_string());
                let done = vec![container(
                    vec![text_display(&format!("**{}** — accepted", merge.path))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!("**{}** — rejected", merge.path))],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    // Review removed files
    for (i, path) in changes.removed.iter().enumerate() {
        let counter = format!("[{}/{}]", changes.clean_merges.len() + i + 1, total);
        let content =
            format!("{counter} **{path}**\nThis file was removed from the default bundle.",);

        let file_id = path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Delete", &format!("bundled_file_accept:{file_id}"), 4),
                    button("Keep", &format!("bundled_file_reject:{file_id}"), 2),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send removal review: {e}");
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                accepted_deletions.push(path.clone());
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — deleted"))],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — kept"))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    UpdateDecision {
        accepted_paths,
        accepted_deletions,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn new_files_detected() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
        assert!(changes.removed.is_empty());
        assert!(!changes.new.is_empty());
    }

    #[test]
    fn unchanged_files_not_flagged() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.new.is_empty());
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
        assert!(changes.removed.is_empty());
    }

    #[test]
    fn modified_workspace_file_not_flagged_without_bundle_change() {
        // User modified a file but bundle hasn't changed — should NOT
        // be flagged (shadow == bundle means no upstream change).
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let first = &bundled_files()[0];
        std::fs::write(dir.path().join(first.path), "user modified content").unwrap();
        let changes = compute_changes(dir.path());
        // Shadow == bundle, so no change detected regardless of workspace
        assert!(changes.auto_updates.is_empty());
        assert!(changes.clean_merges.is_empty());
        assert!(changes.conflicts.is_empty());
    }

    #[test]
    fn removed_bundle_file_detected() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        // Write a shadow for a file no longer in the bundle
        let shadow_dir = dir.path().join(".bundled/skills/old-skill");
        std::fs::create_dir_all(&shadow_dir).unwrap();
        std::fs::write(shadow_dir.join("skill.md"), "old").unwrap();

        // Create the file in workspace too
        let ws_dir = dir.path().join("skills/old-skill");
        std::fs::create_dir_all(&ws_dir).unwrap();
        std::fs::write(ws_dir.join("skill.md"), "old").unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.removed.len(), 1);
        assert_eq!(changes.removed[0], "skills/old-skill/skill.md");
    }

    #[test]
    fn diff_generation_works() {
        let diff = generate_diff("old content\nline 2\n", "new content\nline 2\n");
        assert!(diff.contains("-old content"));
        assert!(diff.contains("+new content"));
    }

    #[test]
    fn apply_updates_installs_new_files() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        let decision = UpdateDecision::accept_all(&changes);
        apply_updates(dir.path(), &changes, &decision).unwrap();

        for file in bundled_files() {
            assert!(
                dir.path().join(file.path).exists(),
                "Missing workspace file: {}",
                file.path
            );
            assert!(
                dir.path().join(".bundled").join(file.path).exists(),
                "Missing shadow file: {}",
                file.path
            );
        }
    }

    #[test]
    fn apply_updates_respects_rejection() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        let first = &bundled_files()[0];

        // Set up a clean-merge scenario using multi-line content:
        // base (shadow) has lines A-B-C, user changed A, bundle
        // changes C — non-overlapping so merge is clean.
        let base = "line A\nline B\nline C\n";
        let user_version = "user A\nline B\nline C\n";
        // Simulate the new bundle having changed line C
        // Since we can't change the actual bundle, we use a
        // different approach: set up so shadow != bundle and
        // workspace != shadow, with changes in different regions
        // to produce a clean merge.
        write_shadow(dir.path(), first.path, base).unwrap();
        std::fs::write(dir.path().join(first.path), user_version).unwrap();

        let changes = compute_changes(dir.path());
        // Shadow ("line A\nline B\nline C\n") != bundle (actual content),
        // workspace ("user A\nline B\nline C\n") != shadow → merge3
        // The merge may be clean or conflict depending on content
        // overlap. Either way, rejecting should not overwrite workspace
        // for clean merges.

        if !changes.clean_merges.is_empty() {
            let decision = UpdateDecision::reject_all();
            apply_updates(dir.path(), &changes, &decision).unwrap();

            // Rejected clean merge: workspace keeps user's content
            let content = std::fs::read_to_string(dir.path().join(first.path)).unwrap();
            assert_eq!(content, user_version);

            // But shadow is updated to new bundle content
            let shadow =
                std::fs::read_to_string(dir.path().join(".bundled").join(first.path)).unwrap();
            assert_eq!(shadow, first.content);
        } else {
            // If it's a conflict, apply_updates always writes conflict
            // content. Verify shadow still gets updated.
            assert!(!changes.conflicts.is_empty());
            let decision = UpdateDecision::reject_all();
            apply_updates(dir.path(), &changes, &decision).unwrap();

            let shadow =
                std::fs::read_to_string(dir.path().join(".bundled").join(first.path)).unwrap();
            assert_eq!(shadow, first.content);
        }
    }

    #[test]
    fn install_all_writes_shadows() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        for file in bundled_files() {
            let shadow = dir.path().join(".bundled").join(file.path);
            assert!(shadow.exists(), "Missing shadow: {}", file.path);
            let content = std::fs::read_to_string(&shadow).unwrap();
            assert_eq!(
                content, file.content,
                "Shadow content mismatch: {}",
                file.path
            );
        }
    }

    #[test]
    fn auto_update_when_user_didnt_modify() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        let first = &bundled_files()[0];
        // Simulate old shadow (different from current bundle)
        let old = "old bundle content";
        std::fs::write(dir.path().join(first.path), old).unwrap();
        write_shadow(dir.path(), first.path, old).unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.auto_updates.len(), 1);
        assert_eq!(changes.auto_updates[0].path, first.path);
    }

    #[test]
    fn install_docs_writes_all_files() {
        let dir = TempDir::new().unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, bundled_docs().len());

        for doc in bundled_docs() {
            let dest = dir.path().join("references/ghost/docs").join(doc.path);
            let content = std::fs::read_to_string(&dest).unwrap();
            assert_eq!(content, doc.content);
        }
    }

    #[test]
    fn install_docs_skips_unchanged() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, 0);
    }

    #[test]
    fn install_docs_removes_stale_files() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file
        let stale = dir.path().join("references/ghost/docs/old-page.md");
        std::fs::write(&stale, "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale.exists(), "stale file should be removed");
    }

    #[test]
    fn install_docs_removes_empty_stale_dirs() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file in a stale subdirectory
        let stale_dir = dir.path().join("references/ghost/docs/old-section");
        std::fs::create_dir_all(&stale_dir).unwrap();
        std::fs::write(stale_dir.join("page.md"), "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale_dir.exists(), "stale directory should be removed");
    }
}
