/// Central registry of all files bundled with the ghost binary.
///
/// The `BUNDLED_FILES` array is auto-generated by `build.rs` from the
/// `assets/` directory. The workspace-relative path of each file equals
/// its path relative to `assets/`. To add a new bundled file, just drop
/// it in `assets/` — no Rust changes needed.
use std::path::Path;

/// A file bundled into the ghost binary via `include_str!`.
pub struct BundledFile {
    /// Workspace-relative path, e.g. "skills/nix-shell/skill.md"
    pub path: &'static str,
    /// File content (from include_str!)
    pub content: &'static str,
}

// Generated by build.rs from assets/ and docs/src/content/
include!(concat!(env!("OUT_DIR"), "/bundled_files.rs"));

/// Returns the complete list of files bundled with this binary.
pub fn bundled_files() -> &'static [BundledFile] {
    BUNDLED_FILES
}

/// Returns the documentation pages bundled with this binary.
pub fn bundled_docs() -> &'static [BundledFile] {
    BUNDLED_DOCS
}

/// Install bundled docs to `references/ghost/docs/` in the workspace.
///
/// Writes only files whose content has changed and removes stale files
/// that are no longer in the bundle, so after this call the directory
/// exactly mirrors the bundled docs.
///
/// Returns the number of files written (new + updated).
pub fn install_docs(workspace: &Path) -> Result<usize, std::io::Error> {
    let docs_dir = workspace.join("references/ghost/docs");
    std::fs::create_dir_all(&docs_dir)?;

    let mut written = 0;

    // Collect the set of expected relative paths for stale-file cleanup
    let mut expected: std::collections::HashSet<std::path::PathBuf> =
        std::collections::HashSet::new();

    for doc in bundled_docs() {
        let dest = docs_dir.join(doc.path);
        expected.insert(dest.clone());

        let needs_write = match std::fs::read_to_string(&dest) {
            Ok(existing) => existing != doc.content,
            Err(_) => true,
        };

        if needs_write {
            if let Some(parent) = dest.parent() {
                std::fs::create_dir_all(parent)?;
            }
            std::fs::write(&dest, doc.content)?;
            written += 1;
        }
    }

    // Remove stale files not in the current bundle
    remove_stale_files(&docs_dir, &expected)?;

    Ok(written)
}

/// Recursively remove files under `dir` that are not in `expected`,
/// then prune empty directories.
fn remove_stale_files(
    dir: &Path,
    expected: &std::collections::HashSet<std::path::PathBuf>,
) -> Result<(), std::io::Error> {
    for entry in std::fs::read_dir(dir)?.filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_dir() {
            remove_stale_files(&path, expected)?;
            // Remove directory if now empty
            if path.read_dir()?.next().is_none() {
                std::fs::remove_dir(&path)?;
            }
        } else if !expected.contains(&path) {
            std::fs::remove_file(&path)?;
        }
    }
    Ok(())
}

/// Install all bundled files to the workspace, always overwriting.
/// Creates parent directories as needed.
pub fn install_all(workspace: &Path) -> Result<(), std::io::Error> {
    for file in bundled_files() {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;
    }
    save_manifest(workspace)?;
    Ok(())
}

/// Save the current bundled file paths as the manifest for future removal detection.
pub fn save_manifest(workspace: &Path) -> Result<(), std::io::Error> {
    let paths: Vec<&str> = bundled_files().iter().map(|f| f.path).collect();
    let json = serde_json::to_string_pretty(&paths).unwrap_or_default();
    let manifest_path = workspace.join(".cache/bundled-manifest.json");
    if let Some(parent) = manifest_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(manifest_path, json)
}

// ── Change detection ────────────────────────────────────────────────

use similar::{ChangeTag, TextDiff};

/// Result of comparing bundled files against the workspace.
pub struct BundledChanges {
    /// Files that exist in bundle but not in workspace.
    pub new: Vec<&'static BundledFile>,
    /// Files that differ between bundle and workspace.
    pub changed: Vec<ChangedFile>,
    /// Paths that were in the previous manifest but are no longer bundled
    /// (and still exist in workspace).
    pub removed: Vec<String>,
}

pub struct ChangedFile {
    pub path: &'static str,
    pub diff: String,
    pub bundled_content: &'static str,
}

impl BundledChanges {
    pub fn has_updates(&self) -> bool {
        !self.changed.is_empty() || !self.removed.is_empty()
    }
}

/// Compare bundled files against the workspace.
pub fn compute_changes(workspace: &Path) -> BundledChanges {
    let mut new = Vec::new();
    let mut changed = Vec::new();

    let current_paths: std::collections::HashSet<&str> =
        bundled_files().iter().map(|f| f.path).collect();

    for file in bundled_files() {
        let dest = workspace.join(file.path);
        match std::fs::read_to_string(&dest) {
            Ok(existing) if existing == file.content => {
                // Unchanged
            }
            Ok(existing) => {
                let diff = generate_diff(&existing, file.content);
                changed.push(ChangedFile {
                    path: file.path,
                    diff,
                    bundled_content: file.content,
                });
            }
            Err(_) => {
                new.push(file);
            }
        }
    }

    // Detect removed bundled files
    let removed = load_manifest(workspace)
        .into_iter()
        .filter(|p| !current_paths.contains(p.as_str()))
        .filter(|p| workspace.join(p).exists())
        .collect();

    BundledChanges {
        new,
        changed,
        removed,
    }
}

/// Generate a unified diff between old (workspace) and new (bundled) content.
pub fn generate_diff(old: &str, new: &str) -> String {
    let diff = TextDiff::from_lines(old, new);
    let mut output = String::new();
    for change in diff.iter_all_changes() {
        let sign = match change.tag() {
            ChangeTag::Delete => "-",
            ChangeTag::Insert => "+",
            ChangeTag::Equal => " ",
        };
        output.push_str(sign);
        output.push_str(change.as_str().unwrap_or(""));
        if !change.as_str().unwrap_or("").ends_with('\n') {
            output.push('\n');
        }
    }
    output
}

fn load_manifest(workspace: &Path) -> Vec<String> {
    let path = workspace.join(".cache/bundled-manifest.json");
    match std::fs::read_to_string(&path) {
        Ok(json) => serde_json::from_str(&json).unwrap_or_default(),
        Err(_) => Vec::new(),
    }
}

/// The user's decisions about which updates to apply.
pub struct UpdateDecision {
    pub accepted_paths: Vec<String>,
    pub accepted_deletions: Vec<String>,
}

impl UpdateDecision {
    pub fn accept_all(changes: &BundledChanges) -> Self {
        Self {
            accepted_paths: changes.changed.iter().map(|c| c.path.to_string()).collect(),
            accepted_deletions: changes.removed.clone(),
        }
    }

    pub fn reject_all() -> Self {
        Self {
            accepted_paths: Vec::new(),
            accepted_deletions: Vec::new(),
        }
    }
}

/// Apply the user's update decisions to the workspace.
pub fn apply_updates(
    workspace: &Path,
    changes: &BundledChanges,
    decision: &UpdateDecision,
) -> Result<(), std::io::Error> {
    // Install new files (always)
    for file in &changes.new {
        let dest = workspace.join(file.path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, file.content)?;
    }

    // Apply accepted changes
    for file in &changes.changed {
        if decision.accepted_paths.contains(&file.path.to_string()) {
            let dest = workspace.join(file.path);
            std::fs::write(&dest, file.bundled_content)?;
        }
    }

    // Apply accepted deletions
    for path in &decision.accepted_deletions {
        let dest = workspace.join(path);
        let _ = std::fs::remove_file(&dest);
    }

    // Save updated manifest
    save_manifest(workspace)?;
    Ok(())
}

// ── Discord update dialog ───────────────────────────────────────────

use crate::interfaces::discord::components_v2::*;
use serenity::http::Http;
use serenity::model::id::ChannelId;

/// Present bundled file changes to the user via Discord and wait for their
/// decision. Returns the set of accepted file paths and accepted deletions.
pub async fn prompt_updates_via_discord(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> UpdateDecision {
    let summary = format!(
        "**Workspace Update Available**\n{} files modified, {} files removed",
        changes.changed.len(),
        changes.removed.len(),
    );

    let components = vec![container(
        vec![
            text_display(&summary),
            action_row(vec![
                button("Accept All", "bundled_accept_all", 3),
                button("Review", "bundled_review", 1),
                button("Reject All", "bundled_reject_all", 4),
            ]),
        ],
        Some(0x5865F2),
    )];

    let msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
        Ok(msg) => msg,
        Err(e) => {
            tracing::error!("Failed to send bundled update dialog: {e}");
            return UpdateDecision::accept_all(changes);
        }
    };

    loop {
        let Some(custom_id) = rx.recv().await else {
            return UpdateDecision::accept_all(changes);
        };

        match custom_id.as_str() {
            "bundled_accept_all" => {
                let done = vec![container(
                    vec![text_display("**Workspace Update** — All changes accepted.")],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return UpdateDecision::accept_all(changes);
            }
            "bundled_reject_all" => {
                let done = vec![container(
                    vec![text_display("**Workspace Update** — All changes rejected.")],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &done).await;
                return UpdateDecision::reject_all();
            }
            "bundled_review" => {
                let reviewing = vec![container(
                    vec![text_display("**Workspace Update** — Reviewing changes...")],
                    Some(0x5865F2),
                )];
                let _ = edit_v2_message(http, channel_id, msg.id, &reviewing).await;
                return review_files(changes, http, channel_id, rx).await;
            }
            _ => continue,
        }
    }
}

/// Present each changed file one by one with Accept/Reject buttons.
async fn review_files(
    changes: &BundledChanges,
    http: &Http,
    channel_id: ChannelId,
    rx: &mut tokio::sync::mpsc::UnboundedReceiver<String>,
) -> UpdateDecision {
    let mut accepted_paths: Vec<String> = Vec::new();
    let mut accepted_deletions: Vec<String> = Vec::new();
    let total = changes.changed.len() + changes.removed.len();

    // Review changed files
    for (i, changed) in changes.changed.iter().enumerate() {
        let counter = format!("[{}/{}]", i + 1, total);

        // Truncate diff for Discord's 4000 char limit
        let diff_display = if changed.diff.len() > 3400 {
            let truncated = &changed.diff[..3400];
            let remaining_lines = changed.diff[3400..].lines().count();
            format!("{truncated}\n... and {remaining_lines} more lines")
        } else {
            changed.diff.clone()
        };

        let content = format!(
            "{counter} **{}**\n```diff\n{}\n```",
            changed.path, diff_display
        );

        let file_id = changed.path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Accept", &format!("bundled_file_accept:{file_id}"), 3),
                    button("Reject", &format!("bundled_file_reject:{file_id}"), 4),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send file review: {e}");
                accepted_paths.push(changed.path.to_string());
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                accepted_paths.push(changed.path.to_string());
                let done = vec![container(
                    vec![text_display(&format!("**{}** — accepted", changed.path))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!("**{}** — rejected", changed.path))],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    // Review removed files
    for (i, path) in changes.removed.iter().enumerate() {
        let counter = format!("[{}/{}]", changes.changed.len() + i + 1, total);
        let content =
            format!("{counter} **{path}**\nThis file was removed from the default bundle.",);

        let file_id = path.replace('/', "_");
        let components = vec![container(
            vec![
                text_display(&content),
                action_row(vec![
                    button("Delete", &format!("bundled_file_accept:{file_id}"), 4),
                    button("Keep", &format!("bundled_file_reject:{file_id}"), 2),
                ]),
            ],
            None,
        )];

        let file_msg = match send_v2_message(http, channel_id, &components, Vec::new()).await {
            Ok(m) => m,
            Err(e) => {
                tracing::error!("Failed to send removal review: {e}");
                continue;
            }
        };

        loop {
            let Some(custom_id) = rx.recv().await else {
                break;
            };
            if custom_id.starts_with("bundled_file_accept:") {
                accepted_deletions.push(path.clone());
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — deleted"))],
                    Some(0xED4245),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            } else if custom_id.starts_with("bundled_file_reject:") {
                let done = vec![container(
                    vec![text_display(&format!("**{path}** — kept"))],
                    Some(0x57F287),
                )];
                let _ = edit_v2_message(http, channel_id, file_msg.id, &done).await;
                break;
            }
        }
    }

    UpdateDecision {
        accepted_paths,
        accepted_deletions,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn new_files_detected() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.changed.is_empty());
        assert!(changes.removed.is_empty());
        assert!(!changes.new.is_empty());
    }

    #[test]
    fn unchanged_files_not_flagged() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let changes = compute_changes(dir.path());
        assert!(changes.new.is_empty());
        assert!(changes.changed.is_empty());
        assert!(changes.removed.is_empty());
    }

    #[test]
    fn modified_workspace_file_detected() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();
        let first = &bundled_files()[0];
        std::fs::write(dir.path().join(first.path), "user modified content").unwrap();
        let changes = compute_changes(dir.path());
        assert_eq!(changes.changed.len(), 1);
        assert_eq!(changes.changed[0].path, first.path);
    }

    #[test]
    fn removed_bundle_file_detected() {
        let dir = TempDir::new().unwrap();
        // Install first so all current files exist
        install_all(dir.path()).unwrap();

        // Now write a manifest that includes an extra path no longer bundled
        let mut paths: Vec<&str> = bundled_files().iter().map(|f| f.path).collect();
        paths.push("skills/old-skill/skill.md");
        let json = serde_json::to_string(&paths).unwrap();
        std::fs::write(dir.path().join(".cache/bundled-manifest.json"), json).unwrap();

        // Create the file so it exists in workspace
        std::fs::create_dir_all(dir.path().join("skills/old-skill")).unwrap();
        std::fs::write(dir.path().join("skills/old-skill/skill.md"), "old").unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.removed.len(), 1);
        assert_eq!(changes.removed[0], "skills/old-skill/skill.md");
    }

    #[test]
    fn diff_generation_works() {
        let diff = generate_diff("old content\nline 2\n", "new content\nline 2\n");
        assert!(diff.contains("-old content"));
        assert!(diff.contains("+new content"));
    }

    #[test]
    fn apply_updates_installs_new_files() {
        let dir = TempDir::new().unwrap();
        let changes = compute_changes(dir.path());
        let decision = UpdateDecision::accept_all(&changes);
        apply_updates(dir.path(), &changes, &decision).unwrap();

        for file in bundled_files() {
            assert!(
                dir.path().join(file.path).exists(),
                "Missing: {}",
                file.path
            );
        }
    }

    #[test]
    fn apply_updates_respects_rejection() {
        let dir = TempDir::new().unwrap();
        install_all(dir.path()).unwrap();

        let first = &bundled_files()[0];
        std::fs::write(dir.path().join(first.path), "user version").unwrap();

        let changes = compute_changes(dir.path());
        assert_eq!(changes.changed.len(), 1);

        let decision = UpdateDecision::reject_all();
        apply_updates(dir.path(), &changes, &decision).unwrap();

        let content = std::fs::read_to_string(dir.path().join(first.path)).unwrap();
        assert_eq!(content, "user version");
    }

    #[test]
    fn manifest_roundtrip() {
        let dir = TempDir::new().unwrap();
        std::fs::create_dir_all(dir.path().join(".cache")).unwrap();
        save_manifest(dir.path()).unwrap();
        let loaded = load_manifest(dir.path());
        let expected: Vec<&str> = bundled_files().iter().map(|f| f.path).collect();
        assert_eq!(loaded, expected);
    }

    #[test]
    fn install_docs_writes_all_files() {
        let dir = TempDir::new().unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, bundled_docs().len());

        for doc in bundled_docs() {
            let dest = dir.path().join("references/ghost/docs").join(doc.path);
            let content = std::fs::read_to_string(&dest).unwrap();
            assert_eq!(content, doc.content);
        }
    }

    #[test]
    fn install_docs_skips_unchanged() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();
        let written = install_docs(dir.path()).unwrap();
        assert_eq!(written, 0);
    }

    #[test]
    fn install_docs_removes_stale_files() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file
        let stale = dir.path().join("references/ghost/docs/old-page.md");
        std::fs::write(&stale, "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale.exists(), "stale file should be removed");
    }

    #[test]
    fn install_docs_removes_empty_stale_dirs() {
        let dir = TempDir::new().unwrap();
        install_docs(dir.path()).unwrap();

        // Create a stale file in a stale subdirectory
        let stale_dir = dir.path().join("references/ghost/docs/old-section");
        std::fs::create_dir_all(&stale_dir).unwrap();
        std::fs::write(stale_dir.join("page.md"), "stale").unwrap();

        install_docs(dir.path()).unwrap();
        assert!(!stale_dir.exists(), "stale directory should be removed");
    }
}
